# Generated by Django 4.1.4 on 2023-02-26 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('name', models.CharField(db_index=True, default='A', max_length=40)),
                ('surname', models.CharField(db_index=True, default='M', max_length=40)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True, verbose_name='City')),
                ('is_business_trip', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='KindOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True, verbose_name='KindOfDay')),
                ('is_working_day', models.BooleanField(default=True)),
                ('is_sick_leave', models.BooleanField(default=False)),
                ('is_vacation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Вид дня',
                'verbose_name_plural': 'Виды дня',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Year number')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Month number')),
                ('name', models.TextField(max_length=20, null=True, verbose_name='Month name')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='working_calendar.year')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяца',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date_of_day', models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='Date')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('working_hours', models.IntegerField(blank=True, default=None, null=True, verbose_name='Hours')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='working_calendar.city')),
                ('kind_of_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='working_calendar.kindofday')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='working_calendar.month')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
    ]
